trigger:
- master

resources:
- repo: self

variables:
  OSVersion: '1803'

jobs:
- job: Windows

  pool:
    vmImage: 'win1803'

  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      containerregistrytype: 'Container Registry'

      dockerRegistryEndpoint: cjcreativetech

      arguments: '--build-arg SERVERCORE_VERSION=$(OSVersion)'

      imageName: '$(Build.Repository.Name):$(OSVersion)'

      qualifyImageName: false

      includeLatestTag: true

  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      containerregistrytype: 'Container Registry'

      dockerRegistryEndpoint: cjcreativetech

      command: 'Push an image'

      imageName: '$(Build.Repository.Name):$(OSVersion)'

      qualifyImageName: false
